# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Contains keypoint csv file for testing .

filegroup(
    name = "data",
    srcs = [
        "bone_config_world_standardized.csv",
        "both_gmm_mixture_5_fixed_r0.100000.pbtxt",
        "pca_bone_config_world.csv",
        "pca_bone_shape_config.csv",
        "simplified_skin_yf_zu.obj",
        "synthetic_mask_0611.png",
        "vertex_weights_simplified_skin.csv",
        "vertex_weights_skeleton_mesh.csv",
    ],
    visibility = ["//visibility:public"],
)
