# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Test data for pose_3d
filegroup(
    name = "data",
    srcs = [
        "bone_config_world.csv",
        "bone_config_world_standardized.csv",
        "gmm_mixture_20_fixed.pbtxt",
        "gmm_mixture_5.pbtxt",
        "labeled_2dkp.csv",
        "pca_bone_config_world.csv",
        "pca_bone_shape_config.csv",
        "test_camera_P3x4.txt",
        "test_mouse_camera_P3x4.txt",
        "test_mouse_skeleton.csv",
        "test_mouse_skeleton_2d.csv",
        "test_skeleton.csv",
        "test_skeleton_2d.csv",
        "test_tri.obj",
        "tri_weights.csv",
    ],
    visibility = ["//visibility:public"],
)
